apiVersion: v1
kind: Service
metadata:
  name: { { include "frontend.fullname" . } }
  labels: { { - include "frontend.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type | default "ClusterIP" } }
  ports:
    - port: { { .Values.service.port | default 80 } }
      targetPort: { { .Values.containerPort | default 3000 } }
      protocol: TCP
      name: http
  selector: { { - include "frontend.selectorLabels" . | nindent 4 } }
